Repository LhexyRomero/CAPSTONE_ZOODIS, pull requests merged in 2018-09, with the labels that each got.

#57 Researcher Side UI#2
  js/controllers/researcher/researcherRoutes.js
  js/public/css/main.css
  js/public/img/intro-carousel/1.jpg
  js/public/img/intro-carousel/2.jpg
  js/public/img/intro-carousel/3.jpg
  js/public/img/intro-carousel/4.jpg
  js/public/img/intro-carousel/5.jpg
  js/public/img/sidebar-1.jpg
  js/public/img/sidebar-2.jpg
  js/public/img/sidebar-3.jpg
  js/public/img/sidebar-4.jpg
  js/public/img/sidebar-5.jpg
  js/views/researcher/index.ejs
Labels: good first issue

#58 Researcher UI#3
  js/controllers/researcher/researcherRoutes.js
  js/public/css/main.css
  js/public/img/about-mission.jpg
  js/public/img/about-plan.jpg
  js/public/img/about-vision.jpg
  js/public/img/mike.jpg
  js/public/img/portfolio/app1.jpg
  js/public/img/portfolio/app2.jpg
  js/public/img/portfolio/app3.jpg
  js/public/img/portfolio/card1.jpg
  js/public/img/portfolio/card2.jpg
  js/public/img/portfolio/card3.jpg
  js/public/img/portfolio/web1.jpg
  js/public/img/portfolio/web2.jpg
  js/public/img/portfolio/web3.jpg
  js/public/img/prada.jpg
  js/public/img/testimonial-1.jpg
  js/public/img/testimonial-2.jpg
  js/public/img/testimonial-3.jpg
  js/public/img/testimonial-4.jpg
  js/public/img/testimonial-5.jpg
  js/views/researcher/about.ejs
  js/views/researcher/blog-home.ejs
  js/views/researcher/blog-single.ejs
  js/views/researcher/contact.ejs
  js/views/researcher/elements.ejs
  js/views/researcher/hotels.ejs
  js/views/researcher/index.ejs
  js/views/researcher/insurance.ejs
  js/views/researcher/microbiota.ejs
  js/views/researcher/packages.ejs
  js/views/researcher/researcher_animal.ejs
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_disease.ejs
Labels: enhancement

#59 Researcher UI#3
  js/views/admin/animal.ejs
  js/views/admin/animalTaxon.ejs
  js/views/admin/bacteria.ejs
  js/views/admin/bacteriaTaxon.ejs
  js/views/admin/disease.ejs
  js/views/admin/diseaseTable.ejs
  js/views/admin/hostTable.ejs
  js/views/admin/journal.ejs
  js/views/admin/notification.ejs
  js/views/admin/prevention.ejs
  js/views/admin/rejectTable.ejs
  js/views/admin/sampleAlgo.ejs
  js/views/admin/staff.ejs
  js/views/admin/toxin.ejs
Labels: good first issue

#60 Admin Side Partials
  js/controllers/researcher/researcherRoutes.js
  js/public/css/bootstrap.css
  js/public/css/main.css
  js/views/admin/animal.ejs
  js/views/admin/animalTaxon.ejs
  js/views/admin/bacteria.ejs
  js/views/admin/bacteriaTaxon.ejs
  js/views/admin/dashboard.ejs
  js/views/admin/disease.ejs
  js/views/admin/diseaseTable.ejs
  js/views/admin/hostTable.ejs
  js/views/admin/journal.ejs
  js/views/admin/notification.ejs
  js/views/admin/prevention.ejs
  js/views/admin/rejectTable.ejs
  js/views/admin/staff.ejs
  js/views/admin/toxin.ejs
  js/views/contributor/contri_Animal.ejs
  js/views/contributor/contri_AnimalTaxon.ejs
  js/views/contributor/contri_Bacteria.ejs
  js/views/contributor/contri_BacteriaTaxon.ejs
  js/views/contributor/contri_Dashboard.ejs
  js/views/contributor/contri_Disease.ejs
  js/views/contributor/contri_Notification.ejs
  js/views/contributor/contri_Prevention.ejs
  js/views/contributor/contri_Toxin.ejs
  js/views/partials/admin_sidebar.ejs
  js/views/partials/contri_sidebar.ejs
  js/views/partials/core_js.ejs
  js/views/partials/head.ejs
  js/views/partials/navbar.ejs
  js/views/researcher/collab.ejs
Labels: enhancement

#61 Researcher Side Partials#1
  js/views/researcher/about.ejs
  js/views/researcher/collab.ejs
  js/views/researcher/contact.ejs
  js/views/researcher/index.ejs
  js/views/researcher/microbiota.ejs
  js/views/researcher/partials/footer.ejs
  js/views/researcher/researcher_animal.ejs
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_disease.ejs
Labels: enhancement

#62 Researcher Side Partials#2
  js/views/researcher/about.ejs
  js/views/researcher/collab.ejs
  js/views/researcher/contact.ejs
  js/views/researcher/index.ejs
  js/views/researcher/microbiota.ejs
  js/views/researcher/partials/head.ejs
  js/views/researcher/partials/header.ejs
  js/views/researcher/researcher_animal.ejs
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_disease.ejs
Labels: enhancement

#63 Researcher and Admin Side Enhancement#1
  js/controllers/admin/notification.js
  js/public/css/bootstrap.css
  js/public/css/main.css
  js/public/js/admin/notification.js
  js/public/js/date.js
  js/public/js/plugins/jasny-bootstrap.min.js
  js/public/js/researcher/journal.js
  js/views/admin/animalTaxon.ejs
  js/views/admin/journal.ejs
  js/views/admin/notification.ejs
  js/views/contributor/contri_Notification.ejs
  js/views/partials/core_js.ejs
  js/views/researcher/collab.ejs
  js/views/researcher/partials/footer.ejs
  js/views/researcher/partials/header.ejs
Labels: bug, help wanted

#64 Admin and Contributor Side Enhancement#1
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/bacteria.js
  js/controllers/contributors/bacteria.js
  js/controllers/contributors/contriRoutes.js
  js/public/js/admin/bacteria.js
  js/public/js/contri_js/bacteria.js
  js/views/admin/dashboard.ejs
  js/views/admin/journal.ejs
  js/views/admin/toxin.ejs
  js/views/contributor/contri_Toxin.ejs
Labels: bug, help wanted

#65 Researcher Login
  .gitignore
  js/controllers/admin/adminRoutes.js
  js/controllers/authentication.js
  js/controllers/contributors/auth.js
  js/controllers/contributors/bacteria.js
  js/controllers/researcher/authentication.js
  js/controllers/researcher/researcherRoutes.js
  js/public/js/contri_js/bacteria.js
  js/public/js/researcher/auth.js
  js/views/contributor/contri_Toxin.ejs
  js/views/login.ejs
  js/views/researcher/about.ejs
  js/views/researcher/index.ejs
  js/views/researcher/partials/footer.ejs
  js/views/researcher/partials/header.ejs
  js/views/researcher/researcher_animal.ejs
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_disease.ejs
  zoodis.sql
Labels: enhancement, help wanted

#66 Researcher Registration
  js/connection.js
  js/controllers/authentication.js
  js/controllers/researcher/researcherRoutes.js
  js/emailer.js
  js/head.js
  js/public/js/researcher/auth.js
  js/views/researcher/partials/header.ejs
  package-lock.json
  package.json
  zoodis.sql
Labels: bug, enhancement

#67 Researcher Authentication #2
  js/controllers/authentication.js
  js/controllers/researcher/journal.js
  js/controllers/researcher/researcherRoutes.js
  js/public/css/main.css
  js/public/js/researcher/auth.js
  js/public/js/researcher/contact.js
  js/public/js/researcher/journal.js
  js/views/researcher/collab.ejs
  js/views/researcher/partials/footer.ejs
  js/views/researcher/partials/header.ejs
Labels: enhancement, help wanted

#68 Researcher w/ Account Contact
  js/controllers/authentication.js
  js/controllers/researcher/contact.js
  js/controllers/researcher/researcherRoutes.js
  js/public/js/researcher/contact.js
  js/public/js/researcher/journal.js
  js/views/researcher/collab.ejs
  js/views/researcher/partials/header.ejs
Labels: enhancement

#69 Contributor and Researcher Side#1
  js/controllers/admin/journal.js
  js/controllers/admin/staff.js
  js/controllers/authentication.js
  js/controllers/contributors/contriRoutes.js
  js/controllers/contributors/disease.js
  js/controllers/contributors/notification.js
  js/controllers/contributors/prevention.js
  js/controllers/researcher/contact.js
  js/controllers/researcher/researcherRoutes.js
  js/public/css/bootstrap.min.css
  js/public/css/now-ui-dashboard.min69ea.css
  js/public/js/contri_js/animal.js
  js/public/js/contri_js/bacteria.js
  js/public/js/contri_js/disease.js
  js/public/js/contri_js/notification.js
  js/public/js/contri_js/prevention.js
  js/public/js/researcher/contact.js
  js/views/admin/journal.ejs
  js/views/contributor/contri_Disease.ejs
  js/views/contributor/contri_Notification.ejs
  js/views/contributor/contri_Prevention.ejs
  js/views/researcher/contact.ejs
  js/views/researcher/partials/header.ejs
Labels: enhancement

#71 Contributor User Profile#2
  js/public/js/contri_js/profile.js
  js/views/contributor/contri_user.ejs
Labels: bug, enhancement, help wanted

#74 Message Notification#1
  js/public/css/now-ui-dashboard.min69ea.css
  js/views/admin/dashboard.ejs
Labels: enhancement

#75 Admin Message Notification#1
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/message.js
  js/public/css/now-ui-dashboard.min69ea.css
  js/public/js/admin/message.js
  js/views/admin/dashboard.ejs
Labels: bug, enhancement

#76 Admin Message Notification #2
  js/controllers/admin/message.js
  js/controllers/researcher/contact.js
  js/public/css/now-ui-dashboard.min69ea.css
  js/public/js/admin/message.js
  js/views/admin/animal.ejs
  js/views/admin/animalTaxon.ejs
  js/views/admin/bacteria.ejs
  js/views/admin/bacteriaTaxon.ejs
  js/views/admin/dashboard.ejs
  js/views/admin/disease.ejs
  js/views/admin/diseaseTable.ejs
  js/views/admin/hostTable.ejs
  js/views/admin/journal.ejs
  js/views/admin/notification.ejs
  js/views/admin/prevention.ejs
  js/views/admin/rejectTable.ejs
  js/views/admin/staff.ejs
  js/views/admin/toxin.ejs
  js/views/admin/user.ejs
  js/views/contributor/contri_Animal.ejs
  js/views/contributor/contri_AnimalTaxon.ejs
  js/views/contributor/contri_Bacteria.ejs
  js/views/contributor/contri_BacteriaTaxon.ejs
  js/views/contributor/contri_Dashboard.ejs
  js/views/contributor/contri_Disease.ejs
  js/views/contributor/contri_Notification.ejs
  js/views/contributor/contri_Prevention.ejs
  js/views/contributor/contri_Toxin.ejs
  js/views/contributor/contri_user.ejs
  js/views/partials/admin_navbar.ejs
  js/views/partials/contri_navbar.ejs
  js/views/partials/navbar.ejs
Labels: enhancement

#77 Admin Message Notification#3
  js/controllers/admin/adminRoutes.js
  js/public/css/now-ui-dashboard.min69ea.css
  js/public/js/admin/message.js
  js/views/admin/message.ejs
  js/views/partials/admin_navbar.ejs
Labels: enhancement, good first issue

#78 Admin Message Notification#4
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/message.js
  js/public/js/admin/message.js
  js/views/admin/message.ejs
  js/views/partials/admin_navbar.ejs
  js/views/partials/contri_navbar.ejs
Labels: enhancement, good first issue

#79 Leki branch
  js/bacdive.js
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/message.js
  js/emailer.js
  js/public/css/now-ui-dashboard.min69ea.css
  js/public/js/admin/message.js
  js/public/js/admin/staff.js
  js/router.js
  js/views/admin/dashboard.ejs
  js/views/admin/message.ejs
  js/views/admin/staff.ejs
  package.json
Labels: enhancement

#80 Leki branch
  js/bacdive.js
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/search.js
  js/public/js/admin/bacteria.js
Labels: enhancement

#82 Leki branch
  js/controllers/admin/journal.js
  js/controllers/contributors/bacteria.js
  js/views/admin/animal.ejs
  js/views/admin/animalTaxon.ejs
  js/views/admin/bacteria.ejs
  js/views/admin/bacteriaTaxon.ejs
  js/views/admin/disease.ejs
  js/views/admin/journal.ejs
  js/views/admin/prevention.ejs
  js/views/admin/toxin.ejs
  js/views/contributor/contri_Animal.ejs
  js/views/contributor/contri_AnimalTaxon.ejs
  js/views/contributor/contri_Bacteria.ejs
  js/views/contributor/contri_BacteriaTaxon.ejs
  js/views/contributor/contri_Disease.ejs
  js/views/contributor/contri_Prevention.ejs
  js/views/contributor/contri_Toxin.ejs
  js/views/contributor/contri_user.ejs
Labels: enhancement, help wanted

#84 Emailer Design Done
  js/controllers/admin/message.js
  js/controllers/admin/staff.js
  js/controllers/authentication.js
  js/views/researcher/index.ejs
  js/views/researcher/partials/footer.ejs
Labels: enhancement

#85 Admin and Contributor Side Enhancement#2
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/animal.js
  js/controllers/admin/bacteria.js
  js/controllers/admin/disease.js
  js/controllers/contributors/bacteria.js
  js/controllers/contributors/contriRoutes.js
  js/controllers/contributors/disease.js
  js/public/js/admin/animal.js
  js/public/js/admin/bacteria.js
  js/public/js/admin/disease.js
  js/public/js/contri_js/bacteria.js
  js/public/js/contri_js/disease.js
  js/views/admin/disease.ejs
  js/views/admin/diseaseTable.ejs
  js/views/admin/hostTable.ejs
  js/views/admin/toxin.ejs
  js/views/contributor/contri_Disease.ejs
  js/views/contributor/contri_Toxin.ejs
Labels: enhancement

#87 Website Landing Page#2
  js/public/css/main.css
  js/views/researcher/index.ejs
Labels: enhancement
