Repository LhexyRomero/CAPSTONE_ZOODIS, pull requests merged in 2018-10, with the labels that each got.

#89 Researcher Disease
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_disease.ejs
Labels: bug

#90 Website Landing Page#4
  js/controllers/researcher/researcherRoutes.js
  js/controllers/researcher/search.js
  js/controllers/researcher/searchingDisease.js
  js/public/js/researcher/diseaseSearch.js
  js/views/researcher/index.ejs
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_disease.ejs
Labels: enhancement, need to focused on

#91 Updated Database
  js/controllers/admin/message.js
  js/controllers/researcher/searchingDisease.js
  js/public/js/admin/message.js
  js/public/js/researcher/animalSearch.js
  js/views/admin/message.ejs
  js/views/researcher/about.ejs
  js/views/researcher/collab.ejs
  js/views/researcher/index.ejs
  js/views/researcher/researcher_animal.ejs
  zoodis.sql
Labels: enhancement, need to focused on

#93 Ib branch
  zoodis.sql
Labels: enhancement

#94 Admin Message#1
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/message.js
Labels: enhancement

#95 Admin and Contributor Side Enhancement#3
  js/controllers/admin/animal.js
  js/controllers/admin/bacteria.js
  js/controllers/admin/disease.js
  js/controllers/admin/notification.js
  js/controllers/admin/prevention.js
  js/controllers/contributors/animal.js
  js/controllers/contributors/bacteria.js
  js/controllers/contributors/disease.js
  js/controllers/contributors/prevention.js
  js/controllers/researcher/contact.js
  js/public/js/admin/journal.js
  js/public/js/admin/notification.js
  js/public/js/admin/reject.js
  js/views/admin/hostTable.ejs
  js/views/admin/notification.ejs
  js/views/admin/rejectTable.ejs
Labels: enhancement

#96 Admin and Contributor Side Enhancement#4
  js/controllers/admin/journal.js
  js/public/js/admin/animal.js
  js/public/js/admin/bacteria.js
  js/public/js/admin/disease.js
  js/public/js/admin/journal.js
  js/public/js/admin/notification.js
  js/public/js/admin/prevention.js
  js/public/js/admin/staff.js
  js/public/js/contri_js/animal.js
  js/public/js/contri_js/bacteria.js
  js/public/js/contri_js/disease.js
  js/public/js/contri_js/prevention.js
  js/views/admin/journal.ejs
  js/views/contributor/contri_Toxin.ejs
Labels: enhancement

#98 Journal Scan
  index.js
  js/controllers/researcher/journal.js
  js/fileUpload.js
  js/head.js
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_disease.ejs
  package-lock.json
  package.json
Labels: enhancement, good first issue, need to focused on

#99 Admin Enhancement#2
  js/public/js/admin/animal.js
  js/public/js/admin/staff.js
Labels: enhancement

#100 Admin and Contributor Side Enhancement#5
  js/controllers/admin/animal.js
  js/controllers/admin/bacteria.js
  js/controllers/contributors/animal.js
  js/controllers/contributors/bacteria.js
  js/controllers/contributors/disease.js
  js/controllers/contributors/prevention.js
  js/public/js/admin/animal.js
  js/public/js/admin/bacteria.js
  js/public/js/admin/disease.js
  js/public/js/admin/journal.js
  js/public/js/admin/prevention.js
  js/public/js/contri_js/animal.js
  js/public/js/contri_js/bacteria.js
  js/public/js/contri_js/disease.js
  js/public/js/contri_js/prevention.js
  js/views/admin/toxin.ejs
Labels: enhancement

#102 Admin and Contributor Side Enhancement#6
  js/public/js/admin/animal.js
  js/public/js/admin/bacteria.js
Labels: enhancement

#103 Admin and Contributor Side Enhancement#7
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/animal.js
  js/controllers/admin/journal.js
  js/controllers/admin/notification.js
  js/controllers/admin/request.js
  js/controllers/authentication.js
  js/controllers/contributors/auth.js
  js/controllers/researcher/journal.js
  js/public/js/admin/animal.js
  js/public/js/admin/journal.js
  js/public/js/admin/message.js
  js/public/js/admin/notification.js
  js/public/js/admin/request.js
  js/views/admin/animal.ejs
  js/views/admin/journal.ejs
  js/views/admin/notification.ejs
  js/views/admin/request.ejs
  js/views/partials/admin_navbar.ejs
  js/views/partials/admin_sidebar.ejs
  js/views/register.ejs
  js/views/researcher/collab.ejs
Labels: enhancement, need to focused on

#104 Flor branch
  js/views/admin/dashboard.ejs
  js/views/contributor/contri_Dashboard.ejs
Labels: enhancement

#105 Admin and Contributor Side Enhancement#8
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/notification.js
  js/controllers/admin/request.js
  js/controllers/contributors/animal.js
  js/controllers/contributors/bacteria.js
  js/controllers/contributors/disease.js
  js/controllers/contributors/prevention.js
  js/controllers/researcher/researcherRoutes.js
  js/controllers/researcher/search.js
  js/controllers/researcher/searchingBacteria.js
  js/public/js/admin/notification.js
  js/public/js/researcher/bacteriaSearch.js
  js/views/researcher/index.ejs
  js/views/researcher/researcher_bacteria.ejs
Labels: enhancement, need to focused on

#106 Admin Enhancement#3
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/bacteria.js
  js/controllers/admin/notification.js
  js/public/js/admin/bacteria.js
  js/public/js/admin/disease.js
  js/views/admin/bacteria.ejs
  js/views/admin/hostTable.ejs
Labels: enhancement, need to focused on

#107 Updated Database
  js/public/js/admin/bacteria.js
  zoodis.sql
Labels: enhancement

#108 Admin and Contributor Side Enhancement#9
  js/controllers/admin/bacteria.js
  js/controllers/admin/notification.js
  js/controllers/contributors/bacteria.js
  js/public/js/admin/bacteria.js
  js/views/admin/bacteria.ejs
  js/views/admin/diseaseTable.ejs
  js/views/admin/hostTable.ejs
  js/views/contributor/contri_Bacteria.ejs
Labels: bug, enhancement, need to focused on

#109 Report Design
  js/controllers/admin/adminRoutes.js
  js/views/admin/reports.ejs
Labels: enhancement

#110 Admin and Contributor Side Enhancement#10
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/bacteria.js
  js/controllers/admin/request.js
  js/controllers/contributors/bacteria.js
  js/controllers/contributors/contriRoutes.js
  js/controllers/contributors/disease.js
  js/controllers/contributors/notification.js
  js/controllers/contributors/search.js
  js/public/js/admin/bacteria.js
  js/public/js/admin/request.js
  js/public/js/contri_js/bacteria.js
  js/public/js/contri_js/disease.js
  js/views/admin/bacteria.ejs
  js/views/admin/hostTable.ejs
  js/views/admin/request.ejs
  js/views/contributor/contri_Bacteria.ejs
  js/views/contributor/contri_Disease.ejs
  zoodis.sql
Labels: bug, enhancement, need to focused on

#111 Enchance Search Algo and Undone fix on upload directory
  .gitignore
  js/controllers/researcher/searchingBacteria.js
  js/fileUpload.js
  js/public/js/contri_js/disease.js
  js/views/contributor/contri_Disease.ejs
  js/views/researcher/researcher_bacteria.ejs
Labels: bug, enhancement, invalid, need to focused on

#113 Admin and Contributor Side Enhancement#11
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/notification.js
  js/controllers/contributors/bacteria.js
  js/controllers/researcher/searchingBacteria.js
  js/public/js/admin/notification.js
  js/public/others/0f41bc38a2f8769.jpeg
  js/public/others/22d22cbc26e948d.jpeg
  js/public/others/28042b2f061349a.jpeg
  js/public/others/2cf066863b4c12a.jpeg
  js/public/others/39af267f7cf7dc4.jpeg
  js/public/others/415e5f4bae590d4.jpeg
  js/public/others/79ffe4f0645b8ba.jpeg
  js/public/others/9a39f0e5126d602.jpeg
  js/public/others/b9c5ace9e9d2646.jpeg
  js/public/others/bcf5bbb664679e7.jpeg
  js/public/others/c1675b6a213317e.jpeg
  js/public/others/ea048baf270523f.jpeg
  js/views/admin/journal.ejs
  js/views/admin/notification.ejs
  js/views/researcher/researcher_animal.ejs
Labels: bug, enhancement, need to focused on

#114 Leki branch
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/notification.js
  js/controllers/contributors/auth.js
  js/controllers/researcher/search.js
  js/public/js/admin/notification.js
  js/public/js/contri_js/notification.js
  js/views/contributor/contri_Dashboard.ejs
  js/views/partials/contri_sidebar.ejs
Labels: bug, enhancement, need to focused on

#115 Admin and Contributor Side Enhancement#12
  js/controllers/admin/adminRoutes.js
  js/controllers/authentication.js
  js/controllers/researcher/search.js
  js/public/js/admin/message.js
  js/views/admin/message.ejs
  js/views/partials/admin_navbar.ejs
  js/views/partials/core_js.ejs
Labels: bug, enhancement, need to focused on

#116 Animal Researcher Search#1
  js/controllers/researcher/searchingAnimal.js
Labels: enhancement, good first issue

#117 Fixes
  js/controllers/researcher/searchingAnimal.js
  js/public/js/admin/animal.js
  js/public/js/contri_js/animal.js
Labels: enhancement, good first issue

#118 Researcher Side Enhancement#1
  js/controllers/researcher/researcherRoutes.js
  js/controllers/researcher/searchingBacteria.js
  js/public/js/researcher/bacteriaSearch.js
  js/views/researcher/researcher_bacteria.ejs
Labels: bug

#119 Researcher Side Enhancement#2
  js/controllers/researcher/researcherRoutes.js
  js/controllers/researcher/searchingAnimal.js
  js/controllers/researcher/searchingBacteria.js
  js/controllers/researcher/searchingDisease.js
  js/public/js/admin/staff.js
  js/public/js/researcher/animalSearch.js
  js/public/js/researcher/bacteriaSearch.js
  js/public/js/researcher/diseaseSearch.js
  js/views/researcher/researcher_animal.ejs
  js/views/researcher/researcher_disease.ejs
Labels: enhancement

#120 fix researcher bacteria search
  js/controllers/researcher/searchingBacteria.js
  js/public/js/researcher/bacteriaSearch.js
  js/views/researcher/researcher_bacteria.ejs
Labels: enhancement

#121 Pdf generator
  js/pdfGenerator.js
  js/public/js/contri_js/notification.js
  package-lock.json
  package.json
Labels: enhancement, need to focused on

#125 Admin and Contributor Side Enhancement#14
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/query.js
  js/controllers/researcher/searchingAnimal.js
  js/controllers/researcher/searchingBacteria.js
  js/public/css/main.css
  js/public/css/now-ui-dashboard.min69ea.css
  js/public/js/admin/query.js
  js/views/admin/dashboard.ejs
  js/views/researcher/researcher_animal.ejs
  js/views/researcher/researcher_bacteria.ejs
Labels: bug, enhancement

#127 Researcher Side Enhancement#3
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/disease.js
  js/controllers/admin/prevention.js
  js/controllers/admin/reject.js
  js/controllers/researcher/query.js
  js/controllers/researcher/researcherRoutes.js
  js/public/js/admin/reject.js
  js/public/js/admin/request.js
  js/public/js/researcher/query.js
  js/views/contributor/contri_Dashboard.ejs
  js/views/researcher/index.ejs
Labels: bug, enhancement, need to focused on

#130 diseases algo
  js/controllers/researcher/searchingDisease.js
Labels: enhancement, good first issue

#133 Updated Database
  js/controllers/researcher/journal.js
  js/controllers/researcher/searchingDisease.js
  js/views/contributor/contri_Dashboard.ejs
  js/views/researcher/index.ejs
  zoodis.sql
Labels: enhancement

#134 Fixing Bugs
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/reports.js
  js/controllers/admin/request.js
  js/controllers/contributors/contriRoutes.js
  js/controllers/contributors/query.js
  js/controllers/researcher/query.js
  js/controllers/researcher/researcherRoutes.js
  js/controllers/researcher/searchingAnimal.js
  js/controllers/researcher/searchingBacteria.js
  js/controllers/researcher/searchingDisease.js
  js/controllers/researcher/searchingToxin.js
  js/public/js/admin/reports.js
  js/public/js/contri_js/query.js
  js/public/js/researcher/bacteriaSearch.js
  js/public/js/researcher/diseaseSearch.js
  js/public/js/researcher/query.js
  js/public/js/researcher/toxinSearch.js
  js/views/admin/dashboard.ejs
  js/views/admin/reports.ejs
  js/views/contributor/contri_Dashboard.ejs
  js/views/researcher/index.ejs
  js/views/researcher/partials/header.ejs
  js/views/researcher/researcher_animal.ejs
  js/views/researcher/researcher_bacteria.ejs
  js/views/researcher/researcher_toxin.ejs
  js/views/researcher/view_bacteria.ejs
  js/views/researcher/view_disease.ejs
  js/views/researcher/view_toxin.ejs
  zoodis.sql
Labels: enhancement, good first issue

#135 Fixing Bugs#2
  js/controllers/admin/adminRoutes.js
  js/controllers/admin/journal.js
  js/controllers/admin/notification.js
  js/controllers/admin/query.js
  js/controllers/contributors/auth.js
  js/controllers/contributors/notification.js
  js/controllers/contributors/query.js
  js/controllers/researcher/journal.js
  js/controllers/researcher/query.js
  js/public/js/admin/notification.js
  js/public/js/contri_js/notification.js
  js/public/js/researcher/journal.js
Labels: enhancement, good first issue

#137 Fixing Bugs#3
  js/controllers/admin/notification.js
  js/controllers/contributors/notification.js
  js/public/img/AU.png
  js/public/img/BR.png
  js/public/img/RO.png
  js/public/img/US.png
  js/public/img/bg1.jpg
  js/public/img/bg13.jpg
  js/public/img/bg14.jpg
  js/public/img/bg15.jpg
  js/public/img/bg16.jpg
  js/public/img/bg3.jpg
  js/public/img/bg5.jpg
  js/public/img/clients/client-1.png
  js/public/img/clients/client-2.png
  js/public/img/clients/client-3.png
  js/public/img/clients/client-4.png
  js/public/img/clients/client-5.png
  js/public/img/clients/client-6.png
  js/public/img/clients/client-7.png
  js/public/img/clients/client-8.png
  js/public/img/faces/avatar.jpg
  js/public/img/faces/card-profile1-square.jpg
  js/public/img/faces/card-profile2-square.jpg
  js/public/img/faces/face-0.jpg
  js/public/img/faces/face-1.jpg
  js/public/img/faces/face-2.jpg
  js/public/img/faces/face-3.jpg
  js/public/img/faces/face-4.jpg
  js/public/img/faces/face-5.jpg
  js/public/img/faces/face-6.jpg
  js/public/img/faces/face-7.jpg
  js/public/img/faces/marc.jpg
  js/public/img/faces/tim_vector.jpe
  js/public/img/saint-laurent.jpg
  js/public/js/admin/notification.js
  js/views/admin/dashboard.ejs
Labels: enhancement

#139 Fixing Bugs#4
  js/controllers/admin/animal.js
  js/controllers/admin/bacteria.js
Labels: enhancement

#140 Reliable Data
  js/controllers/researcher/searchingDisease.js
  js/views/admin/reports.ejs
  zoodis.sql
Labels: enhancement

#141 Revision#1
  js/controllers/admin/bacteria.js
  js/controllers/admin/disease.js
  js/controllers/admin/journal.js
  js/controllers/admin/notification.js
  js/controllers/admin/reports.js
  js/controllers/admin/request.js
  js/controllers/admin/staff.js
  js/controllers/authentication.js
  js/controllers/contributors/notification.js
  js/public/js/admin/notification.js
  js/public/js/contri_js/notification.js
  js/views/admin/notification.ejs
  js/views/admin/reports.ejs
  js/views/contributor/contri_Dashboard.ejs
  js/views/partials/admin_sidebar.ejs
Labels: enhancement

#142 Leki branch
  js/controllers/contributors/autocomplete.js
  js/controllers/contributors/contriRoutes.js
  js/public/js/contri_js/autocomplete.js
  js/views/contributor/contri_AnimalTaxon.ejs
  js/views/contributor/contri_BacteriaTaxon.ejs
  js/views/partials/contri_sidebar.ejs
  zoodis.sql
Labels: enhancement

#143 Revision#4
  js/controllers/admin/request.js
  js/controllers/contributors/contriRoutes.js
  js/controllers/contributors/notification.js
  js/public/js/admin/request.js
  js/public/js/contri_js/notification.js
  js/views/admin/request.ejs
  js/views/contributor/contri_Notification.ejs
Labels: enhancement
